# <div class = "alert alert-info"> NumPy Introduction

### <div class = "alert alert-success"> What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

### <div class = "alert alert-success"> Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.
    
### <div class = "alert alert-success">Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

### <div class = "alert alert-success">Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

### <div class = "alert alert-success">Where is the NumPy Codebase?
The source code for NumPy is located at this github repository https://github.com/numpy/numpy

### <div class = "alert alert-danger">Import NumPy
Once NumPy is installed, import it in your applications by adding the <span style="color:red">
import
    </span> keyword:


In [3]:
import numpy as np  # NumPy is imported and ready to use.

# NumPy is usually imported under the np alias.

In [5]:
arr = np.array([1, 2, 3, 4, 5])     #array is equivalent to list

print(arr)

[1 2 3 4 5]


# <div class = "alert alert-info">NumPy Creating Arrays
    
- Create a NumPy ndarray Object:
    
    NumPy is used to work with arrays. The array object in NumPy is called ndarray.
    We can create a NumPy ndarray object by using the <span style="color:red">array() </span>  function.

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the <span style="color:red">array() </span>  method, and it will be converted into an ndarray:

In [7]:
print(np.array((1, 2, 3, 4, 5)))

[1 2 3 4 5]


###   <div class = "alert alert-danger">Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

<div class = "alert alert-warning"> Nested array: are arrays that have arrays as their elements.<div>

In [10]:
arr0 = np.array(42)

print(arr0)

42


### 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [11]:
# Create a 1-D array containing the values 1,2,3,4,5:

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

[1 2 3 4 5]


### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

<div class = "alert alert-warning"> NumPy has a whole sub module dedicated towards matrix operations called <span style="color:red">numpy.mat</span> 

In [12]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [13]:

# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


###   <div class = "alert alert-danger">Check Number of Dimensions?
NumPy Arrays provides the <span style="color:red">ndim </span>attribute that returns an integer that tells us how many dimensions the array have.

In [17]:
# Check how many dimensions the arrays have:

print("array 0D:",arr0.ndim)
print("array 1D:",arr1.ndim)
print("array 2D:",arr2.ndim)
print("array 3D:",arr3.ndim)

array 0D: 0
array 1D: 1
array 2D: 2
array 3D: 3


###   <div class = "alert alert-danger"> Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the  <span style="color:red">ndim </span> argument.

In [18]:
arry = np.array([1, 2, 3, 4], ndmin=5)

print(arry)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 1


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.